-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    amount double precision,
    CONSTRAINT payments_pk PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id bigint NOT NULL,
    max_number_of_users integer NOT NULL,
    salary double precision NOT NULL,
    CONSTRAINT roles_pk PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.sent_emails
(
    email_id bigint NOT NULL,
    user_id bigint NOT NULL,
    email_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    confirmation_code character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sent_emails_pk PRIMARY KEY (email_id)
);

CREATE TABLE IF NOT EXISTS public.sick_notes
(
    user_id bigint NOT NULL,
    sick_note_id bigint NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sick_notes_pk PRIMARY KEY (sick_note_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    birth_date date NOT NULL,
    register_date date NOT NULL,
    is_enabled boolean NOT NULL,
    is_acc_locked boolean NOT NULL,
    CONSTRAINT users__pk PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_payments_payment_id_fk FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sent_emails
    ADD CONSTRAINT sent_emails_sent_emails__fk FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sick_notes
    ADD CONSTRAINT sick_notes_sick_notes__fk FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users__fk FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;