spring:
  application:
    name:
      crowdcontrol
  datasource:
    url:
    username:
    password:
  jpa:
    open-in-view: false
#    properties:
#      hibernate:
#        dialect:
#          org.hibernate.dialect.PostgreSQLDialect