spring:
  application:
    name:
      crowdcontrol
  datasource:
    url:
    username:
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
crowdcontrol:
  vars:
    SECRET_KEY: "" # Define here your 256 secret key for JWT.